### ISSUE TITLE
selectingMultipleBamAsInputFails

### ISSUE THREAD

**Issue by jfy133** [apeltzer/EAGER-GUI#15]
If the parent directory of multiple sample directories of bams is selected as input (as works with FastQ), and then 'Generate Config File' if pressed, no EAGER result directories are created in the ouput directory.

Selecting a single BAM file directly correctly generates a Config File.

EAGER-GUI version: 1.92.7

**Comment by apeltzer** [comment]
Adressed in 912a82a29d39dd7d0d248604974ae02372a8fea0 and af72b6544f3672db1838ac4b512fbf92a459b469 now :-) Please test!
