### ISSUE TITLE
Colour Of Input Buttons After 'Generate Config File' Remains Green

### ISSUE THREAD

**Issue by jfy133** [apeltzer/EAGER-GUI#21]
When setting up an EAGER run, once the button goes green this does not reset (or go to another colour e.g. orange) after pressing 'generate config file'.

This can be confusing when setting up multiple EAGER runs from the same GUI instance (e.g. mapping the same set of samples to different reference sequences), as it is hard to to know whether you have correctly re-selected the new reference or output directory.

**Comment by apeltzer** [comment]
This has been adressed and fixed in 8e71652d065ea1e5eeb222b1c8ed7bec41c6e640 , in the next upcoming release (with some smaller testing changes to test the GUI automatically), this will be adressed - thanks for the comment !

**Comment by apeltzer** [comment]
Apparently, this is more for reference file(s) and not for the input file(s) to quickyl map against different types of reference genome(s).

**Comment by apeltzer** [comment]
Properly adressed now in 72b79eedc29611b62240f2fc3bec44ce76c965bf
