### ISSUE TITLE
wrong Configuration Exception

### ISSUE THREAD

**Issue by alex-seitz** [apeltzer/EAGER-GUI#27]
When starting EAGER with single-end reads, one get the error exception that no reads could be found. However the configs are generated successfully. This leads to confusion

**Comment by JudithNeukamm** [comment]
I think the problem is in Class "EAGER.java". 

 Line 621 should be 
"if (communicator.getGUI_inputfiles().size() <= 1 && communicator.isPairmenttype()) {"

instead of 

"if (communicator.getGUI_inputfiles().size() <= 1"
