### ISSUE TITLE
Singularity exec failed

### ISSUE THREAD

**Issue by aakechin** [apeltzer/EAGER-GUI#37]
I installed singularity version 2.3.1. 
Then downloaded EAGER with `singularity pull shub://apeltzer/EAGER-GUI:master` and tried to run `singularity exec -B /path/to/your/data:/data /home/<username>/Downloads/apeltzer-EAGER-GUI-master.img eager` but it shows the following error:
`/.singularity.d/actions/exec: line 8: exec: eager: not found`. 
What can I do to solve this problem? Than you in advance!
I have Ubuntu 16.04.

**Comment by apeltzer** [comment]
Hi! I currently have some issues with Singularity hub hosting the images. I'll create a new one and can send you a link if you send me an email ... (alexander.peltzer AT uni-tuebingen.de) asap.

**Comment by apeltzer** [comment]
Will investigate this, but currently not even the login to singularity hub works (downtime?)

**Comment by aakechin** [comment]
I've sent my e-mail!

**Comment by ghost** [comment]
Hello,

I installed singularity and then when I do:
 singularity pull shub://apeltzer/EAGER-GUI:master
I get this message : ERROR Cannot find image. Is your capitalization correct?
Do you know what it could be the problem?
Thank you very much!

**Comment by apeltzer** [comment]
Please remove the ":master" from your call and run instead:

`singularity pull shub://apeltzer/EAGER-GUI`

I will update this in the README.

**Comment by ghost** [comment]
Thank you!
It worked.
________________________________
De: Alexander Peltzer <notifications@github.com>
Enviado: terça-feira, 3 de julho de 2018 17:57
Para: apeltzer/EAGER-GUI
Cc: silviagui; Comment
Assunto: Re: [apeltzer/EAGER-GUI] Singularity exec failed (#37)


Please remove the ":master" from your call and run instead:

singularity pull shub://apeltzer/EAGER-GUI

I will update this in the README.

**Comment by ghost** [comment]
ust one more question:

the file that I obtained is called:
apeltzer-EAGER-GUI-master-latest.simg*

When I try the next step, to run GUI, it says:
ERROR  : No program name to exec
ABORT  : Retval = 255

Do I need to do something to make it executable?
Thanks a lot!
________________________________
De: Sílvia Guimaraes <biguimaraes@hotmail.com>
Enviado: quarta-feira, 4 de julho de 2018 10:18
Para: apeltzer/EAGER-GUI
Assunto: RE: [apeltzer/EAGER-GUI] Singularity exec failed (#37)

Thank you!
It worked.
________________________________
De: Alexander Peltzer <notifications@github.com>
Enviado: terça-feira, 3 de julho de 2018 17:57
Para: apeltzer/EAGER-GUI
Cc: silviagui; Comment
Assunto: Re: [apeltzer/EAGER-GUI] Singularity exec failed (#37)


Please remove the ":master" from your call and run instead:

singularity pull shub://apeltzer/EAGER-GUI

I will update this in the README.

**Comment by apeltzer** [comment]
Hi Silvia,

did you do something like this

singularity exec apeltzer-EAGER-GUI-master-latest.simg eager

? That should execute the GUI inside the container.

Cheers,

Alex

**Comment by zhongxing123** [comment]
Hello,
I installed singularity and then when I do:
singularity pull shub://apeltzer/EAGER-GUI:master
I get this message : FATAL:   While pulling shub image: failed to get manifest for: shub://apeltzer/EAGER-GUI: 403 Forbidden
Do you know what it could be the problem?
Thank you very much!

**Comment by apeltzer** [comment]
The Singularity Hub images could potentially be non-available or blocked. Maybe consider using eager2 => 

https://github.com/nf-core/eager

(as this isn't in development anymore).
