### ISSUE TITLE
greyed-out 'VCF2Genome' checkbox

### ISSUE THREAD

**Issue by wresch** [apeltzer/EAGER-GUI#38]
Hi,

i'm running through the tutorial with one of the medieval m. leprae samples. When creating the configuration xml file, as soon as i select fastq files, the VCF2Genome checkbox is greyed out (deactivated).

I can edit the xml file to activate the VCF2Genome module and it appears to run without encountering any issues.

I use version 1.92.37 from singularity hub.

Screenshots for the GUI before and after selecting fastq files
![before](https://user-images.githubusercontent.com/272760/45105755-fe578680-b102-11e8-95bf-dea6ebb64384.png)
![after](https://user-images.githubusercontent.com/272760/45105766-03b4d100-b103-11e8-98b5-0f60fa5e43b4.png)

**Comment by apeltzer** [comment]
In order to get the VCF2Genome option, you'd need to select "SNP Calling" with UnifiedGenotyper once. Then it should be enabled. Note, that I'm working on a successor pipeline so will most likely just fix things if they are severe bugs. Let me know if the hint already helped - I was on vacation till today so just saw your email.

**Comment by apeltzer** [comment]
cross referencing the new repository (will most likely have a prototype in the next weeks... feel free to join in too: https://github.com/nf-core/eager )

**Comment by wresch** [comment]
Hi Alexander,

i should have attached a better screen shot - still happens when SNP calling is first selected:
![screenshot from 2018-09-11 07-47-15](https://user-images.githubusercontent.com/272760/45358275-f41c0900-b596-11e8-9884-db5e29db4e61.png)

However, if i open the drop-down for SNP calling and select UnifiedGenotyper again even though it's the default, the VCF2Genom option becomes available.

Since you are working on a rewrite, i'd say that's not worth fixing.

Wolfgang

**Comment by apeltzer** [comment]
Hi Wolfgang,
sorry that was exactly the problem that I didn't explain entirely -yes, after "reselecting" the uNifiedGenotyper again, it should be available again. 

Yeah, I'll probably not fix this anymore as it is (although unfortunately not very userfriendly) "working". My bad... but stay tuned for the rewrite :-)
